#!/usr/bin/env bash
# Install and configure Nginx
apt-get update
apt-get install -y nginx
cat >/etc/nginx/sites-available/default <<'EOL'
server{listen 80 default_server;listen [::]:80 default_server;server_name _;root /var/www/html;index index.html;location / {try_files $uri $uri/ =404;}}
EOL
service nginx restart
